version: '3'
services:
  # db:
  #   image: postgres:9.6
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./postgres-data:/var/lib/postgresql/data

  # rails:
  #   build:
  #     context: rails/.
  #   working_dir: /mnt/rails
  #   env_file: .rails_env
  #   command: bundle exec rails s -p 5000 -b '0.0.0.0'
  #   volumes:
  #     - ./rails:/mnt/rails
  #   links:
  #     - db
  #   depends_on:
  #     - db

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      # - rails
      - web

  web:
    build: ./web
    # depends_on:
    #   - rails
    command: npm start
