# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9e17feba65f548a023ff59e38962c70c31e102c63b48f9f58b29b9759954d9845a79c91c56b3bbdcbdbb8827e8d4a08fd0e8602ec0d78ab75641c1ca093bbc0

test:
  secret_key_base: 6d73acefd12b537228f7e0580b7537be8362e89f9417243ac06861c9d782647b69457de208d0b913ef1dfdf1eb2e3e4012cc2b76f04750f12a55ae672774bf31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
