source "https://rubygems.org"

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

gem "rails", "~> 5.0.7"
gem "puma", "~> 3.0"
gem "pg"

gem "dotenv-rails"
gem "jbuilder", "~> 2.5"
gem "redis", "~> 3.0"
gem "rack-cors"
gem "interactor-rails"
gem "decent_decoration" #, github: "kaikash/decent_decoration" #, branch: "decent-exposure-3-0"
gem "decent_exposure"
gem "knock"
gem "bcrypt-ruby"
gem "kaminari"
gem "draper", github: "audionerd/draper", branch: "rails5"
gem "activemodel-serializers-xml", github: "rails/activemodel-serializers-xml"
gem "validate_url"
gem "roo"
gem "roo-xls"

group :development, :test do
  gem "byebug", platform: :mri
end

group :development do
  gem "listen", "~> 3.0.5"
  gem "spring"
  gem "spring-watcher-listen", "~> 2.0.0"
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]
